### PR TITLE
449: Support JSON serialization of ushort SmartEnums

### LINKED ISSUE #449: ushort error in SmartFlagEnumValueConverter
There is no ushort case in the Write function.

### PR DESCRIPTION
**Pull request by sdepouw**
- Fixes #449
- `ushort` `SmartEnum` types are now supported in `System.Text.Json` writing/serialization

### CODE REVIEW

**Comment by sdepouw** [comment]
@ardalis fix is complete, but looks like `main` has build failures. Lots of "this publicly-visible member should have XML documentation" on it (which show up after fixing the current error that points out an XML doc type issue).

After those are resolved this should build and work.

**Comment by ardalis** [comment]
Yeah I turned on warnings as errors yesterday but somehow those didn't immediately appear...

**Comment by ardalis** [comment]
Ok, @sdepouw can you have a look at the branch fixing-errors and see if you can knock some more out? I got most of them...

**Comment by sdepouw** [comment]
@ardalis think this one's good to go

**Comment by ardalis** [comment]
Thanks!

**Pull request merged**
