### PR TITLE
Added SmartFlagEnum Functionality

### PR DESCRIPTION
**Pull request by AFM-Horizon**
Hi Guys/Ardalis!
I've been plugging away at the **SmartFlagEnum** Functionality and have come up with a version 1.0!
I decided to create a seperate class and minimize the changes to the original SmartEnum class.  
There is some duplication but this way there is less chance of breaking the current build.  

I'm not sure if this was the right decision but I played around with a few different inheritance and interface options and wasn't really happy with them, (due to the fact that SmartFlagEnums return IEnumerable<TEnum> and the classes were static so overriding didn't seem like a good option.)
  
If anyone has any suggestions or issues with the way I've implemented the changes please let me know! I'm more than happy to jump back in a make changes wherever required.  

**Some information:**
- I have included an update to the README that can help explain the changes along with the code
- I have created a new SmartFlagEnum class that implements the new functionality
- I have created an empty ISmartEnum Interface which both SmartEnum and SmartFlagEnum implement; this allows them to share the ThrowHelper and SmartEnumThen/When classes
- I have duplicated Unit Tests for the SmartFlagEnum class allowing these tests to change seperately from the original test suite
- I have created a new version of the JsonNet Utility and JsonNetUnitTests that works with the SmartFlagEnum class
- I have NOT yet implemented the other utilities for SmartFlagEnums but am more than happy to do so.
- I rebased 27 smaller commits into the one to make it look a little more organised (that was my first time doing that and it was very scary!!) - I'm hoping this doesn't cause any issues.  
  
Hopefully everything is reasonably self explanatory within the code itself!
I look forward to any feedback or change requests
Thanks 
Alex

### CODE REVIEW

**Comment by ardalis** [comment]
Hoping to look at this soon!

**Comment by AFM-Horizon** [comment]
Great! Ill start to implement the other utility classes and push them up as well so no pressure!

**Comment by AFM-Horizon** [comment]
Hi Steve and Team.
Please pardon my lack of movement on this over the past month!  
I jumped in and finished up the
Serialization and AutoFixture Utiliies, they are tested and looking ready to go.  

The only thing that hasn't been completed in terms of the SmartFlagEnum is the benchmarks. 
I will learn how to do this and add them as well when possible!

Thanks!

**Comment by syedsuhaib** [comment]
This is a brilliant piece of work to make SmartEnums smarter! Thanks.

My two cents worth: why is negative 1 being hard-coded to represent all values? I normally use Integer.MaxValue (or the maximum allowable value in case of other base types). This is logical because a value of 255 for example for a byte enum would mean all flags are set (11111111). Given you are throwing SmartFlagEnumDoesNotContainPowerOfTwoValuesException, I am not sure how easy it will be for you to implement this since MaxValue will almost always be one less than a power of two.

**Comment by AFM-Horizon** [comment]
> This is a brilliant piece of work to make SmartEnums smarter! Thanks.
> 
> My two cents worth: why is negative 1 being hard-coded to represent all values? I normally use Integer.MaxValue (or the maximum allowable value in case of other base types). This is logical because a value of 255 for example for a byte enum would mean all flags are set (11111111). Given you are throwing SmartFlagEnumDoesNotContainPowerOfTwoValuesException, I am not sure how easy it will be for you to implement this since MaxValue will almost always be one less than a power of two.

**Comment by AFM-Horizon** [comment]
Hi @syedsuhaib, I did some cursory research on the internet and I was under the impression that the normal functionality of C# flag enum is to use -1 to represent all values.  I could have a look at implementing this as a possibility as well perhaps though, it does make sense what your saying!
the algorithm that checks for power of two values could be adapted to ignore the max.value so that it wont throw an exception, or your welcome to add to the code if you want to!.  
It is pretty heavily covered by unit tests so Hopefully (crossed fingers) it should be easy enough to make changes and at least know whether they have broken the build or not haha.  
I'm also looking to add some benchmark testing to see how it fairs compared with the basic smart enum and with this in mind I have provided some attributes that can be set to disable the negative and power of two checking so the code is written in a flexible manner to allow changes.

**Comment by syedsuhaib** [comment]
> or your welcome to add to the code if you want to!

Actually, I do want to try and give it a go. But it is my first time, so I'm not sure how to get started. Since this PR is not yet merged into the ardalis:master, I'll probably need to fork your fork. But how would I handle any changes that you may make hereafter or do I keep up with any changes on the master?

**Comment by AFM-Horizon** [comment]
@syedsuhaib I'm pretty new to Git in general but I believe you are correct.  I might do a few things here and there but am not planning any major works (unless you find any serious problems that need an overhaul).  I will keep this branch up to date with the original and you can push to this branch as you see fit.  Most of the Smart Flag functionality is parallel to the Original Smart Enum Code so they are pretty well seperated.  Just to let you know that you might want to try to add the max value feature but still keep the negative one as well if possible! as I know that some people also like this functionality!  Let me know how you travel with it!  Look forward to working with you.  
Alex

**Comment by syedsuhaib** [comment]
Just wondering why you're using `int` throughout your implementation of `SmartFlagsEnum` to parse values. Won't it overflow when the underlying type is `long` and a sufficiently large number of members are defined for the enum? Perhaps we could write a test to catch this case…

**Comment by ardalis** [comment]
I guess in theory you're correct but I have to think that if you're exceed MaxInt with your number of enumeration options, you're probably misusing enums.

**Comment by AFM-Horizon** [comment]
@syedsuhaib and @ardalis.  Hmm yeah I am looking at this now I may have made a mistake in using int32 instead of int64 I have effectively halved the possible enum options.  
It could be changed I think but will require changing all of the serialization classes, as well as the code within the SmartFlagEngine.  Unfortunately I made a rookie mistake (likely one of many!) of not abstracting my calls to int32.parse() so they are peppered all over the engine code and will be a bit of a pain to track down and change.  :(

**Comment by syedsuhaib** [comment]
Agreed about misusing enums at that scale. Nevertheless, since SmartEnums do not bar one from using `long` as the base type, it is a bit strange that it should throw up an exception when one chooses to use it in a certain way. I believe a vehicle should work as promised in different situations. It's good and bad use - and the consequences thereof - are for the user to bear.

**Comment by AFM-Horizon** [comment]
@syedsuhaib So you are suggesting to remove the InvalidValueCastException() and let the framework Exception happen naturally? since it will happen regardless of whether we throw the exception?

**Comment by syedsuhaib** [comment]
Fundamental to flagged enums is the ability to perform bitwise operations. We must overload definitions for at least three operators - `&`, `|`, and `~` before this becomes useful. Else, we're leaving users to perform bitwise operations on underlying types, pretty much defeating the purpose of using enums.  Also having `HasFlag()`, `AddFlag()`, and `RemoveFlag()` functions as I have suggested (#67) would ease the usage much.

**Comment by AFM-Horizon** [comment]
@syedsuhaib I agree with the 3 operators! I will work on allowing users to work that way without needing to cast (not explicitly at least).  Right now the only way to do that is using the FromValue() method and casting each value:
`FromValue((int)FlagEnumDecimal.One | (int)FlagEnumDecimal.Two)`

**Comment by chaughawout** [comment]
#104 might benefit from details here.

**Comment by ardalis** [comment]
I'd like to take the time to review this soon (and apologies for not getting to it before now!). Can someone update to resolve conflicts and bring in the latest code? Thanks!

**Comment by ardalis** [comment]
I think #160 covered this - let me know if I can close.

**Pull request closed without merging**
