### PR TITLE
Add de/serializers for JSON.NET

### PR DESCRIPTION
**Pull request by aalmada**
Adds support for de/serialization based on the Newtonsoft.Json library without breaking the SmartEnum design. No need to add a default contructor, add attributes, make mutable properties or create new instances of the enums when deserializing.

This PR adds a new Nuget package that depends on SmartEnum and Newtonsoft.Json. It contains two converters. One uses the value of the enum while the other uses the name. These can be set by using the JsonConverterAttribute. 

Given the `TestEnum` that is a SmartEnum:

```csharp
public sealed class TestEnum : SmartEnum<TestEnum, int>
{
    public static TestEnum One = new TestEnum(nameof(One), 1);
    public static TestEnum Two = new TestEnum(nameof(Two), 2);
    public static TestEnum Three = new TestEnum(nameof(Three), 3);

    private TestEnum(string name, int value) : base(name, value)
    {
    }
}
```
 and the following `TestClass` containing a public property of type `TestEnum` 
```csharp
public class TestClass
{
    [JsonConverter(typeof(SmartEnumValueConverter))]
    public TestEnum SerializeValue { get; set; }
}
```
the following
```csharp
Console.WriteLine(JsonConvert.SerializeObject(new TestClass { SerializeValue = TestEnum.Three  }));
```
will output
```json
{"SerializeValue":"3"}
```

If changed to 
```csharp
public class TestClass
{
    [JsonConverter(typeof(SmartEnumNameConverter))]
    public TestEnum SerializeValue { get; set; }
}
```
will output
```json
{"SerializeValue":"Three"}
```

Both converters can also deserialize. References to the static instances will be returned. No new instances will be created.

Current implementation uses reflection which is not very performant but it can be improved in future versions without breaking changes.

### CODE REVIEW

**Comment by aalmada** [comment]
Replaced the reflection code by dynamically generated code using expression trees. This improves considerably the performance.

Added support for token types other than string for values. The example from above will now output:

```json
{"SerializeValue":3}
```

Added a guard clause for null names in the `SmartEnum` constructor. The method `FromName` had it already. This is breaking change but I think it's the expected behavior.

**Comment by aalmada** [comment]
Performance of value deserialization of a smart enum is now equivalent to the enum.

screenshot at oct 03 16-50-28

**Comment by aalmada** [comment]
`IsSmartEnum()` returns true if a `Type` derives from `SmartEnum<,>`, otherwise false. This requires the methods to go down the hierarchy to find the response. This is a performance issue with de/serializers.

This last commit adds the interfaces `ISmartEnum` and `ISmartEnum<>`, implemented by all smart enums. This allows `IsSmartEnum()` to have only a call to `Type.GetInterface()` (no loops).

The existence of this interfaces also simplifies the serialization. No need to use reflection or dynamic code generation.

**Comment by ardalis** [comment]
Looks good. Sorry for the delay in reviewing. I'm fine with adding an interface for `ISmartEnum` / `ISmartEnum<>`

**Pull request closed without merging**
