### PR TITLE
cache and reuse scanned enum options

### PR DESCRIPTION
**Pull request by norvegec**
Since `GetAllOptions()` method
- performs assembly scan
- is private
- used 3 times in the class
it makes sense to cache it's result.

### CODE REVIEW

**Comment by norvegec** [comment]
Could be superseded with #100

**Comment by chaughawout** [comment]
#104 might benefit from some details here.

**Comment by norvegec** [comment]
This PR 
- contains non-functional, performance improvements
- doesn't contain breaking changes
- all tests are passed
@ardalis what else is required to move forward with it? Since you are the author and maintainer, could you give some feedback?

**Comment by ardalis** [comment]
Sorry - maintaining a bunch of projects and this one has fallen behind in my rotation of keeping things updated.

**Review by ardalis — APPROVED** [review]

**Comment by ardalis** [comment]
Thanks! Will try to get a new release out with this fix soon.

**Pull request merged**
