### PR TITLE
SmartEnum.EFCore + SmartEnum.EFCore.UnitTests

### PR DESCRIPTION
**Pull request by mjuen**
Let’s face it. Configuring a huge amount of properties with special requirements in Entity Framework Core is time consuming, sometimes error prone, and in general annoying. If you want to use SmartEnum in this environment, you have to deal exactly with above-mentioned problems every time you are using the enum in an entity. This PR aims to eliminate the hassle and provide a convenient way for configuring all SmartEnums at once with one single line of code. It adds the new project `SmartEnum.EFCore` together with `SmartEnum.EFCore.UnitTests`.

Just use 

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    ...
    
    modelBuilder.ConfigureSmartEnum();
}
```

at the end of the `OnModelCreating` method and you are good to go. 

Take a look at it and tell me what you think :)

### CODE REVIEW

**Comment by yarrgh** [comment]
This is very cool!

My only suggestion is that you update the README to include your sample code and how to install the package. Assuming that this would be it's own package (which it should be)

**Comment by ardalis** [comment]
This looks great there's only one thing I'd change before merging which is pretty simple. Can we not put SqlLite and Migrations and EF into the UnitTests project, since these all are external dependencies, and instead create a new IntegrationTests project side-by-side with UnitTests and move those tests and their dependencies there? Thanks!

**Comment by ardalis** [comment]
@mjuen do you have time to make the updates I asked for?

**Comment by ardalis** [comment]
Ok, can someone help get this over the finish line?

**Comment by mjuen** [comment]
> 
> 
> @mjuen do you have time to make the updates I asked for?

Sorry, I'm busy at the moment, but feel free to adjust everything to your needs.

**Comment by rsunde** [comment]
Just got stuck on an issue that this PR fixes, its a shame 18 months later its not done yet...

**Comment by hanslai** [comment]
does SmartEnum.EFCore make it into release?  Couldn't find it in Nuget.

**Comment by ardalis** [comment]
Someone could please resolve conflicts and update this to use the current code, and we could merge it in. Otherwise in a month or two I will close this.

**Comment by Yaevh** [comment]
sorry for the mess regarding closing/reopening pull requests, I got a little confused about how to submit a pull request to another pull request. @ardalis, could you please take a look at #142?

**Comment by mjuen** [comment]
Implemented by @Yaevh via #142

**Pull request closed without merging**
