### PR TITLE
Net7 Update

### PR DESCRIPTION
**Pull request by ardalis**

### CODE REVIEW

**Comment by nsulikowski** [comment]
Is version 7.0.0 also compatible with NET 6?

**Comment by nsulikowski** [comment]
Thank you for clarifying. 
Nice library. It'd seem to me that Microsoft should add this to the language itself!
Thanks for making it available.

**Comment by syedsuhaib** [comment]
I may be wrong in understanding the impact of this, but it seems this move may discourage a vast number of potential users from adopting SmartEnum into their existing projects - given net7 itself is not an LTS release. I followed the simple `Install-Package Ardalis.SmartEnum` from readme and it failed for my net6 project (as expected); but that's enough discouragement for a newbie to give up.

If we're currently not using any new features of net7 that make SmartEnum a better deal than without those, we could consider marking the NuGet package with net7 dependency as a preview until net8 LTS is released later this year.

**Comment by ardalis** [comment]
Yeah, it may have been premature for me to update it to net7; I was trying to keep it supporting the latest framework (and align its version with the current dotnet version) while letting folks continue with their previous version if they were already using it. I didn't really consider that it might be more difficult for folks on LTS builds to use it. If nothing else I should add instructions to the README for how to use the latest version that supports net6...

Thanks for the feedback!

**Pull request merged**
