### PR TITLE
Add netstandard2.0 support

### PR DESCRIPTION
**Pull request by ThumNet**
As described in #530

### CODE REVIEW

**Comment by ardalis** [comment]
I was just going to ask in the issue how many changes were needed, and here you beat me to it...

**Review by ardalis — APPROVED** [review]

**Comment by ardalis** [comment]
Looks good to me...

**Comment by ThumNet** [comment]
Thank you for approving!

Build is failing due to a todo in the code, removed that locally to get it building as well. But did not want to check that in.

**Comment by fizmhd** [comment]
@ardalis looking for this change badly.
any updates on this ?
Thanks

**Pull request merged**
