### PR TITLE
Missing nuget packages for integration projects

### PR DESCRIPTION
**Pull request by danielmeza**
As I said in #40 I reorganize the solution to be more devops friendly so:
-Bring solution to the root path
- Create benchmarks folder and move project
- Move test projects from src/test to test
- Reorder projects inside solutions
- Create global Directory.Build.props to simplify project configuration
- Create a src Directory.Build.props to put all package data. 
- Craete Directory.Build.props for tests projects and propagate code
coverage and commons nuget packages.
-Update azure .ylm pipeline to produce code coverage diagrams and result

### CODE REVIEW

**Comment by danielmeza** [comment]
@ardalis Check this! 
image

**Comment by ardalis** [comment]
I'll try and get this merged soon.

**Comment by ardalis** [comment]
Thanks and sorry for the delay!

**Comment by danielmeza** [comment]
Shall we update the readme to include the support for all those frameworks?

**Pull request merged**
