### PR TITLE
Introduce a way to enumerate the enum values without memory allocation

### LINKED ISSUE #494: Add a way to enumerate over the List to prevent allocation every time List is called
Introduce a way to enumerate the enum values without unnecessary memory allocation. This will be useful especially for scenarios requiring frequent iteration. 

I'd happily do a PR if that's okay. 
Something like this:

```cs
public static IEnumerable<TEnum> EnumerateList() => _fromName.Value.Values;
````

### LINKED ISSUE #521: Avoid creating a new list on SmartEnum.List
The `SmartEnum.List` currently is implemented as follows.

```csharp
public static IReadOnlyCollection<TEnum> List =>
    _fromName.Value.Values
        .ToList()
        .AsReadOnly();
```

This API might be frequently called by the consumers, and creating a new list doesn't make much sense. Moreover, this is a property, and the consumer expects that the properties return precalculated fields. They shouldn't contain heavy operations or create additional allocations. If that's the case, then usually the API should be defined as a method, e.g. `GetList()`.

We already keep the collection of discovered enums as `Lazy<TEnum[]>`. But, even internally this collection is never altered, so I suggest the state be kept as `ReadOnlyCollection` instead of an array, and `List` simply would return this field.

```csharp
static readonly Lazy<ReadOnlyCollection<TEnum>> _enumOptions = 
    new Lazy<ReadOnlyCollection<TEnum>>(GetAllOptions, LazyThreadSafetyMode.ExecutionAndPublication);
	
public static IReadOnlyList<TEnum> List => _enumOptions.Value;
``` 

Note: The `ReadOnlyCollection` is proposed since not all targetted TFMs support newer collection types.

### PR DESCRIPTION
**Pull request by akarboush**
Fixes #494 
Fixes #521

### CODE REVIEW

**Review by ardalis — APPROVED** [review]

**Comment by fiseni** [comment]
We don't need to expose a new API here. Instead, we need to fix the `SmartEnum.List`. Right now, it reads from the `_fromName` dictionary and creates a brand new list for the output.
That's unnecessary, we already hold an `_enumOptions` field which is the list of all enums. So, we need only the following fix

```csharp
public static IReadOnlyCollection<TEnum> List => _enumOptions.Value;
```

**Comment by akarboush** [comment]
@fiseni, you are actually correct! I completely overlooked the _enumOptions option. 
 I'll go ahead with it if that's alright with you, @ardalis.

**Comment by fiseni** [comment]
@akarboush @ardalis 
There is more to it. I created issue #521 describing the details and the proposed changes.

**Review by fiseni — APPROVED** [review]
In the related issue, I suggested returning `IReadOnlyList` so the users may use also `for`  iteration. Since it inherits from `IReadOnlyCollection` it won't be a breaking change.

Also, I suggested keeping the state as `ReadOnlyCollection`, otherwise the users will be able to cast back to an array.

Anyhow, @ardalis  let's merge this PR as is. We'll tackle those details additionally.

**Comment by ardalis** [comment]
Done

**Pull request merged**
