### PR TITLE
Add guard clauses for SmartEnum

### LINKED ISSUE #528: Add Guard fro SmartEnum Out of Range
Plase add a guard for Smart Enums Out of Range, just like a regular enum.

Please refer to original discussion at https://github.com/ardalis/GuardClauses/issues/346#issuecomment-2137649866

### PR DESCRIPTION
**Pull request by Asafima**
Added SmartEnumOutOfRange using Ardalis.GuardClauses with two method overloads (int, and generic type).

Closes #528 

#### TODO: Update Readme.md once this pull request is approved and nuget is created.

### CODE REVIEW

**Comment by Asafima** [comment]
@ardalis Hey Ardalis,
Saw you tried to merge the pull request. The build fails because of System.Text.Json vulnerability.
Do you need me to do anything with this pull request?

**Comment by ardalis** [comment]
Update System.Text.Json if you have a chance otherwise I'll get to it eventually.

**Comment by Asafima** [comment]
@ardalis , I have fixed the CS1591 (warning as error).
1. Do you want me to add a publish-smartenumguardclauses.yml file (using the same template you use for all publish ymls)?
2. Do you want me to add a README.md to the SmartEnumGuardClauses csproj? or maybe update it to use the main README file?currently no project has a README file baked into it except for SmartEnum.

**Comment by ardalis** [comment]
@Asafima 
1. Sure that would be helpful.
2. Your call on the README. Probably good for it to have its own and just link to SmartEnum for more info. Would keep it shorter/simpler.

**Comment by Asafima** [comment]
Awesome. Added github-actions yml file for pipeline, and a readme file for this nuget with references to SmartEnum.

**Comment by Asafima** [comment]
@ardalis Hey, any new on this PR?

**Comment by ardalis** [comment]
Thanks!

**Pull request merged**
