### PR TITLE
Move EfCore tests from src/ directory to test/

### PR DESCRIPTION
**Pull request by Khaon**
* Renamed project folder from "SmartEnum.EFCore.UnitTests" to "SmartEnum.EFCore.IntegrationTests" too match Dapper & match root namespace
* Move the project code from "src/" folder to "test/" folder

### BEFORE:
image

### AFTER:
image

### CODE REVIEW

**Review by ardalis — APPROVED** [review]

**Comment by ardalis** [comment]
If you can fix the conflict (should be quick) I'll merge this. Thanks!

**Comment by Khaon** [comment]
Done. :)

**Comment by Khaon** [comment]
Updated to main.

**Comment by ardalis** [comment]
thanks!

**Pull request merged**
