### PR TITLE
Re-target to net452

### PR DESCRIPTION
**Pull request by arootbeer**

### CODE REVIEW

**Comment by ardalis** [comment]
I assume you're stuck on 4.5.2 and this is necessary for you to be able to use this library?

**Comment by arootbeer** [comment]
You've got it. Based on the minimal change footprint, I figured it was worth asking for.

**Comment by arootbeer** [comment]
In case I need to point it out, I didn't update anything related to the NuGet configuration. If you want to tell me what's necessary, I will, but I don't have any experience with package versioning and I didn't want to commit a broken config.

**Comment by ardalis** [comment]
I'll take care of the nuget bits - I just need to modify the version and create a new release. Might no happen today, but soon.

**Comment by arootbeer** [comment]
Thanks, and no worries. The project I'm working on is greenfield, so I'm referencing the locally built version for now.

**Pull request merged**
